module.exports = {
  SERVER_ERROR: 'Что-то пошло не так',
  VALIDATION_ERROR: 'Переданы некорректные данные',
  BAD_DATA: 'Введены неверные данные',
  VIDEO_NOT_FOUND: 'Видео не найдена',
  FORBIDDEN_DELETE_MOVIE: 'Вы не можете удалить чужую карточку',
  BAD_ID_MOVIE: 'Неверный id карточки с фильмом',
  USER_NOT_FOUND: 'Пользователь не найден',
  USED_EMAIL: 'Почта уже зарегестрирована ранее',
  BAD_REGISTRATION: 'Неприравильный логин или пароль',
  NOT_AUTHORIZED: 'Необходима авторизация',
  BAD_ROUTER: 'Запрашиваемый ресурс не найден',
  RATE_LIMIT: 'Превышено количество запросов с одного ip адреса',
  EMAIL_IS_BUSY: 'Email уже используется',
  BAD_URL_IMAGE: 'Неправильный url картинки к фильму',
  BAD_URL_TRAILER: 'Неправильный url трейлера',
  BAD_URL_THUMBNAIL: 'Неправильный url миниатрюры',
  BAD_VALID_EMAIL: 'Неправильный формат почты',
};
